### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by Markjcp** [bytefish/JSqlServerBulkInsert#8]
I have a problem with JSqlServerBulkInsert. I am tring to map VARCHAR(2), VARCHAR(1) and VARCHAR(14) columns but i think the mapString it is only for NVARCHAR(8) columns. Is this correct? Have you tested with diferente varchar columns?

**Comment by vslee** [comment]
Looks like you're right, the mapString currently only supports NVARCHAR. If you'd like to add a pull request for supporting VARCHAR of various lengths, we'd be happy to accept your PR.

**Comment by Markjcp** [comment]
I have tested changing the database column definition. I change all to NVARCHAR(255) and it works but it would be nice to specify a length for varchar columns

**Comment by vslee** [comment]
If you give it a shot and get stuck, send the PR anyways and I'll help you finish it.

**Comment by Markjcp** [comment]
I'll give it a try. Just a question, if i have VARCHAR(x). The "x" is scale or precision property for the sql record interface?

**Comment by vslee** [comment]
Good question. Might have to try them both out to see which ends up working.

**Comment by Markjcp** [comment]
I think is precision. Look at this: https://www.javatips.net/api/mssql-jdbc-master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java 
To the method: writeTypeInfo the case-> **_case java.sql.Types.VARCHAR: // 0xA7_**

**Comment by Markjcp** [comment]
I have modified and pushed to my fork (https://github.com/Markjcp/JSqlServerBulkInsert). I do not have a local database to test it at work, i 'll try to test it at night (i am at GMT-3) but if you can do it early better

**Comment by vslee** [comment]
I tried out your fork. Thanks for adding the test. The test passes, so as long as you're testing your particular scenario, you can go ahead and send the PR. It is interesting to note that I did change the code to set scale instead of precision and the test still passes. I also tried setting both to zero (in the code, not in the DDL) and it still works. So bcp must not be very picky with what those parameters are, as long as the DDL specifying the column to be created is set correctly to begin with.

**Comment by Markjcp** [comment]
I think it would be better for me to test my scenario creating a local release. Tomorrow I'll give you feedback

**Comment by vslee** [comment]
Yes, that would be great.

**Comment by bytefish** [comment]
What I saw is, that most of the examples didn't pass a Precision, when mapping to a Varchar. I suggest the following API change: In the PgBulkInsert API I also started with mapString(...) and so on, but this turned out confusing. Is it a Varchar? Is it Text? Is it NVarchar? Is it Char? I decided to name the methods exactely like this: ``mapVarchar``, ``mapNVarchar``, so it is crystal clear what they map to. The same should be done for the API at hand I think. That would also avoid confusion like in this ticket?

While being at it in this ticket, we could also extend the API surface?

@Markjcp @vslee What do you think?

**Comment by vslee** [comment]
I was thinking along those lines too. The only drawback is that it would be a breaking change for anyone who is already using mapString(). Since this library doesn't appear to have many users at this time, now would be the time to make the change.

**Comment by bytefish** [comment]
Great! Yes and then we should bump the version number 2.0. I can do a first version this weekend and we can iterate on it... or the other way around. ✌️

**Comment by Markjcp** [comment]
Wait, wait. I could not reproduce the original bug. I think the precision is generated automatically with the string length and in my case there was another error. I´ll test one thing and post again.

**Comment by bytefish** [comment]
Nono, @Markjcp. This was a general discussion. I will create a new ticket for it. Thanks for your feedback. 😎

**Comment by bytefish** [comment]
@Markjcp If it's OK for you, I would like to close the ticket and track it with Issue #10. This ticket will remove the problems with Varchar / NVarchar, because of an updated Mapping API. Thanks for raising the issue! 👍

**Comment by bytefish** [comment]
@Markjcp The version 2.0 is now available with an improved API. It should fix the problems. Please reopen the ticket, if the issue persists. 👍
